on:
  push:
    branches: [develop]

name: Deploy "AlteaCare Dashboard Frontliner & Login" to Development Environment on Vercel

jobs:
  deploy:
    name: Deploy "AlteaCare Dashboard Frontliner & Login" to Development Environment on Vercel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          # APPS PORT
          envkey_LOGIN_PORT: ${{ secrets.LOGIN_PORT }}
          envkey_FRONTLINER_PORT: ${{ secrets.FRONTLINER_PORT }}

          # APPS DOMAIN
          envkey_NEXT_PUBLIC_BASE_URL_AUTHENTICATION: ${{ secrets.LOGIN_AUTHENTICATION_BASE_URL_DEV }}
          envkey_NEXT_PUBLIC_BASE_URL_FRONT_LINER: ${{ secrets.FRONT_LINER_BASE_URL_DEV }}

          # COOKIE DOMAIN
          envkey_NEXT_PUBLIC_COOKIE_DOMAIN: sehatdigital.com

          # SERVICE
          envkey_NEXT_PUBLIC_BASE_URL_APPOINTMENT_SERVICE: https://dev-services.alteacare.com/appointment
          envkey_NEXT_PUBLIC_BASE_URL_USER_SERVICE: https://dev-services.alteacare.com/user
          envkey_NEXT_PUBLIC_BASE_URL_SENDER_SERVICE: https://dev-services.alteacare.com/sender
          envkey_NEXT_PUBLIC_BASE_URL_CMS_SERVICE: https://dev-services.alteacare.com/data
          envkey_NEXT_PUBLIC_BASE_URL_SOCKET_SERVICE: https://dev-services.alteacare.com/socket
          envkey_NEXT_PUBLIC_BASE_URL_BILLING_SERVICE: https://dev-services.alteacare.com/billing
          envkey_NEXT_PUBLIC_BASE_URL_MARKETING_SERVICE: https://dev-services.alteacare.com/marketing
          envkey_NEXT_PUBLIC_BASE_URL_FILE_SERVICE: https://dev-services.alteacare.com/file
          envkey NEXT_PUBLIC_BASE_URL_PARTNER_SERVICE: https://dev-services.alteacare.com/partner


      - name: Deploy Athena to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID_ATHENA }}
          alias-domains: dev-athena.sehatdigital.com
          working-directory: ./
          scope: ${{ secrets.TEAM_ID }}
          github-comment: false

      - name: Deploy Aphrodite to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID_APHRODITE }}
          alias-domains: dev-aphrodite.sehatdigital.com
          working-directory: ./
          scope: ${{ secrets.TEAM_ID }}
          github-comment: false

      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: 'deployment-information'
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: 'AlteaCare Bot'
          SLACK_ICON: 'https://alteacare-assets.s3.ap-southeast-1.amazonaws.com/images/logo_48x48.png'
          SLACK_FOOTER: 'AlteaCare Deployment Information'
